# Generated by cucumber-sinatra. (2014-04-19 16:25:11 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/family_weekend.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = FamilyWeekend

class FamilyWeekendWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  FamilyWeekendWorld.new
end
